### ISSUE TITLE
feature request: No Boarder / Boarder Adjustments 

### ISSUE THREAD

**Issue by TheKartel** [discord-extensions/essence#10]
This set of themes has quickly become a favorite, would there be any way to add an option to remove the colorful boarders or adjust the width of them? 

Awesome work!

**Comment by LuckFire** [comment]
i added some variables that should allow you to do this in v1.1.0, you can add this below all of the imports in the theme file:

```css
:root {
    --essence-app-rounding: 6px;
    --essence-app-padding: 18px;
}
```
to completely remove it just set them to 0px, it **has** to be 0px otherwise it just won't work properly
