### ISSUE TITLE
how do i remove the background 

### ISSUE THREAD

**Issue by OnixIsNotaViruss** [discord-extensions/essence#24]
how do i remove the background liek which is colored it makes discord weird so yeah tell the solution im on stable replugged

**Comment by LuckFire** [comment]
add this (below any @imports) in your custom css
```css
:root {
    --essence-app-background-image: none;
}
```
