### ISSUE TITLE
window buttons out of order

### ISSUE THREAD

**Issue by miltoz** [discord-extensions/essence#25]
can u change the Minimize, maximize, Close buttons because they are not in the supposed order [https://imgur.com/a/YXaQh13](url)

**Comment by LuckFire** [comment]
no

**Comment by LuckFire** [comment]
however you can add this to your custom css if you want it to be in the original order
```css
#app-mount .typeWindows-2-g3UY .winButton-3UMjdg:nth-child(4) {
     order: 1;
}
```
